openapi: 3.0.0
info:
  version: 1.0.0
  title: Инфообмен анонсами. API 3PL Avito.
  
paths:
  /delivery/receiveAnnouncement:
    post:
      tags: [Создание и трекинг анонсов]
      operationId: ReceiveAnnouncement
      summary: Метод для создания анонса
      description: Создает анонс о планируемой отгрузке в системе Авито. После успешного создания, анонс направляется в службу доставки указанную в поле "receiver".
      parameters: [ ]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReceiveAnnouncementRequest'
        required: true
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: Internal error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Требуется аутентификация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuth'
        '403':
          description: Неверный токен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuth'        
  /delivery/trackAnnouncement:
    post:
      tags: [Создание и трекинг анонсов]
      operationId: TrackAnnouncement
      summary: Метод для приема событий по анонсу
      description: Принимает события по анонсу от СД
      parameters: [ ]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrackAnnouncementRequest'
        required: true
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: Internal error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Требуется аутентификация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuth'
        '403':
          description: Неверный токен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuth' 
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
          properties:
            status:
              type: string
              description: Статус выполнения запроса.
              enum:
                - success
                - failed
        error:
          type: object
          nullable: true
          properties:
            code: 
              type: string
              description: Код ошибки
              example: "VALIDATION_ERROR"
            message:
              type: string
              description: Текстовое описание ошибки
              example: Текст ошибки
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          nullable: true
          properties:
            code: 
              type: string
              description: Код ошибки
              example: "INTERNAL_ERROR"
            message:
              type: string
              description: Текстовое описание ошибки
              example: Текст ошибки
    ErrorAuth:
      type: object
      nullable: true
      required:
        - message
      properties:
        message:
          type: string
          description: человекопонятное описание ошибки
          example: человекопонятное описание ошибки
        status:
          type: boolean
          description: false в случае возникновения ошибки
          example: false
    TrackAnnouncementRequest:
      type: object
      required:
        - announceID
        - date
        - event
      properties:
        announceID:
          $ref: '#/components/schemas/UUID'
        date:
          allOf:
            - $ref: '#/components/schemas/DateWithTz'
          description: Дата события
        event:
          type: string
          enum:
            - ACCEPTANCE_DONE
            - CANCELLED
            - DELIVERED
            - RECEIVED
    ReceiveAnnouncementRequest:
      type: object
      required:
        - announceID
        - sender
        - receiver
        - announceType
        - date
        - packages
      properties:
        announceID:
          $ref: '#/components/schemas/UUID'
        sender:
          allOf:
            - $ref: '#/components/schemas/DeliveryParticipant'
          example: |-
            {
              "type": "3PL",
              "name": "ExMail",
              "phones": ["8-800-200-00-00"],
              "email": "mail@exmail.ru",
              "delivery": {
                "type": "SORTING_CENTER",
                "sortingCenter": {
                  "provider": "exmail",
                  "id": "010",
                  "accuracy": "EXACT"
                }
              }
            }
        receiver:
          allOf:
            - $ref: '#/components/schemas/DeliveryParticipant'
          example: |-
            {
              "type": "3PL",
              "name": "Почта России",
              "phones": ["8-800-300-00-00"],
              "email": "mail@pochta.ru",
              "delivery": {
                "type": "SORTING_CENTER",
                "sortingCenter": {
                  "provider": "exmail",
                  "id": "19310",
                  "accuracy": "EXACT"
                }
              }
            }
        announceType:
          type: string
          description: Тип анонса
          enum:
            - DELIVERY
        date:
          allOf:
            - $ref: '#/components/schemas/DateWithTz'
          description: Дата и время создания анонса
        packages:
          type: array
          description: Список грузомест
          items:
            allOf:
              - $ref: '#/components/schemas/Package'
    Package:
      type: object
      required:
        - id
        - sealID
        - parcelIDs
      properties:
        id:
          type: string
          description: Идентификатор грузоместа
          example: "package1"
        sealID:
          type: string
          description: Номер пломбы
          example: "1234-5678"
        parcelIDs:
          type: array
          description: Список посылок
          items:
            type: string
          example: ["P000123", "P000345"]
    DateWithTz:
      type: string
      example: "2023-09-20T10:00:00.52Z"
    UUID:
      type: string
      description: Уникальный идентификатор анонса
      example: "55fefb84-fa30-47ee-bf29-9c860823ea79"
    DeliveryParticipant:
      type: object
      required:
        - type
        - name
        - phones
        - delivery
      properties:
        type:
          type: string
          description: Тип отправителя/получателя
          enum:
            - 3PL
        name:
          type: string
          description: Наименование участника доставки (наименование СД)
        phones:
          type: array
          description: Контактные телефоны
          items:
            type: string
        email:
          type: string
          description: Адрес электронной почты
        delivery:
          type: object
          required:
            - type
          properties:
            type:
              type: string
              description: Тип доставки
              enum:
                - SORTING_CENTER
            sortingCenter:
              type: object
              nullable: true
              required:
                - provider
                - id
                - accuracy
              description: Информация о сортировочном центре, заполняется если тип доставки SORTING_CENTER
              properties:
                provider:
                  type: string
                  description: Код службы доставки
                id:
                  type: string
                  description: Идентификатор сортировочного центра
                accuracy:
                  type: string
                  description: Точность указания сортировочного центра
                  enum: 
                    - EXACT
                    - APPROXIMATE